### PR TITLE
Show js contracts

### PR DESCRIPTION
**Pull request by netoneko**

### CODE REVIEW

**Comment by gilamran** [comment]
@netoneko , can  you give some description to the PR?

**Comment by netoneko** [comment]
@gilamran sure!

Right now the only type of contracts that can be displayed are contracts that have language type 1, golang.

I have removed this restriction allowing to display language type 2, javascript.

**Comment by gilamran** [comment]
@netoneko According to what I see in your changes, you've removed the `lang` parameter from the Mongo Query, but still the function signature looks like this: ` getDeployContractTx(contractName: string, lang: number)`. With the lang parameter.

What am I missing here?

**Comment by netoneko** [comment]
@gilamran you are correct: I should've update the interface and all the implementations.

Please take a look now, everything should be fixed.

**Pull request merged**
